site_name: "Documentación"
repo_url: https://github.com/Tknika/5g-docs
site_author: Tknika
repo_name: Tknika/5g-docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences